server:
  port: 8761 # 유레카 서버가 동작되는 서버의 포트 지정. 보통 8761 포트를 많이 사용한다.

spring:
  application:
    name: eureka-service # Application 이름을 지정

eureka:
  client:
    register-with-eureka: false # 해당 서버를 클라이언트로 동작시키겠냐는 설정
    fetch-registry: false # 디스커버리에 등록할건지 설정
