server:
  port: 7090

spring:
  application:
    name: delivery-service

eureka:
  instance:
    instance-id: delivery-microservice-instance
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
